### ISSUE TITLE
Error prebuilding on windows

### ISSUE THREAD

**Issue by fox1t** [NatWeiss/RapidGame#19]
Hi i have this issue when i try to use: rapidgame prebuild

It says 4 errors. Checking the build.log it says
c:\users\maksim\appdata\roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\base\ccconsole.h(42): fatal error C1083: Cannot open include file: 'thread': No such file or directory [C:\Users\maksim\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\editor-support\spine\proj.win32\libSpine.vcxproj]

**Comment by samoersnaes** [comment]
Hey there!

Can I ask what Windows version you're using? Also, have you run tried creating a project with `rapidgame create` or have you only run `rapidgame prebuild`? The first command will automatically prebuild the libraries and also do a one-time setup of a couple other things that the second command may not get to. Also, be sure you're running as administrator.

If you could send me the whole `build.log` file, that'd be great! The more info, the better.

**Comment by fox1t** [comment]
Hi, of course i'll paste you the entire file. I am now trying to compile default cocos 3.6 on my system and it drops same error. I have installed vs2010, vs2013 and vs2015(which i want to test and start using soon). 
https://gist.github.com/fox1t/c25bc26523dd47d2558d
Sorry for the italian language, but the system i am using now isn't in english :/

**Comment by fox1t** [comment]
VS2015 just finished to compile. I have 1844 errors! O_o the one that is generated above is on line 42 #include <thread>

There are also some other random errors... Do you have some advice on how to figure what i'm doing wrong?
I just downloaded rapidgame and tried to rapidgame create ... and to rapidgame prebuild(since create failed). Then i tried to download cocos from the site, but it seems that i have the same problem. :/

**Comment by samoersnaes** [comment]
I'm on it right now. I can actually do Skype or some voice service where I could see your screen so we could work it out in real time. The main problem of course is that I don't see the header files being copied over in the `build.log` file. Is that the entire contents of the file?

**Comment by fox1t** [comment]
Yea it is the full file.  We can skype i can't talk atm but i can write.

**Comment by samoersnaes** [comment]
As you can see, this is what the first few lines of output look like on my machine. ![](https://cloud.githubusercontent.com/assets/5471308/8604346/56fdc0b4-267e-11e5-8691-5b9fc9c8697b.PNG) I doubt it should matter that you're running VS2015, whereas I'm running VS2012. Also, since you just told me that's the whole file, then the problem is the cocos files aren't being downloaded/copied correctly.

**Comment by fox1t** [comment]
Hmmm add me to skype: maksim.sinik

**Comment by samoersnaes** [comment]
For anyone who happens across this page:

We found out the problem lied with using VS2015 as the IDE that compiled cocos2d-x for Windows. Vanilla cocos2d-x itself cannot even be built for Windows using VS2015, so RapidGame cannot build it either. In order to fix the problem, you need to be using VS2012 or VS2013 (can be downloaded for free [here](https://www.visualstudio.com/en-us/products/free-developer-offers-vs.aspx)).

**Comment by samoersnaes** [comment]
Thanks again for figuring it out and good luck man!
