### ISSUE TITLE
Exclude certain resources

### ISSUE THREAD

**Issue by jonnyijapan** [NatWeiss/RapidGame#24]
Can we use this: http://www.cocos2d-x.org/wiki/How_to_exclude_files_in_resources_directory_when_building_for_android

?

Specifically the iOS app included resolution files 1x, 2x and 3x, but since the Google Play Store only supports 50 MB app size, we consider deleting the 3x folder from the res folder. It looks like build-cfg.json from the method above would work, can it be used still or is there another way?

**Comment by jonnyijapan** [comment]
I added this to makefile all/release/distribution for now: **find ./assets/Assets/res -name 3x | xargs rm -fr**

**Comment by samoersnaes** [comment]
It's entirely up to you what resolutions/devices you want to support. If your project does become too big, you can submit multiple .apk's as per [this link](http://developer.android.com/google/play/publishing/multiple-apks.html) in the Android README, meaning you don't necessarily need to delete all the highest res images. In addition, Android handles different resolution assets differently than iOS by putting the files for one intended resolution in one folder, while iOS looks for images with either no suffix, "@2x", or "@3x", depending on the size of the screen of the device the app is running on. However, we're getting out of the realm of what RapidGame is intended for. The template project that's provided is well within the size requirements for both app stores and is meant to be an example project that runs on all possible devices, meaning both phones, hi-res phones, and tablets.

Btw, all the command does is delete files with "3x" in them.

**Comment by jonnyijapan** [comment]
Ok I guess http://www.cocos2d-x.org/wiki/How_to_exclude_files_in_resources_directory_when_building_for_android cannot be used with RapidGame because it uses another way of building the app?

**Comment by jonnyijapan** [comment]
just FYI - The thing about 3x, 2x, 1x etc is not my question, just a side note to explain why I needed to exclude certain assets. The res folder includes sprite atlases (not individual sprite files) for each scene. The res includes 3x, 2x and 1x version of each atlas. The 3x was used for iPhone 6 Plus, the 2x for most other, 1x for iPad mini - this is for iOS of course - I designed the game for iOS in mind. I am using the same assets to speed up development. For high DPI Android screens I use 3x, for medium DPI 2x and so on. I don't use a hardcoded design size, rather each device uses its own native screen size, which is why I could not use the default setup of RapidGame. Of course I could have mistaken something but with my current setup should not have any screen ratio problems.

**Comment by samoersnaes** [comment]
Hey! First off, sorry if my last comment sounded a bit negative. I had some other stuff going on that had me in a really bad mood.

Anyway, for your particular case, the link I sent you before should help you with your problem. You don't have to build a single .apk for your app. You can submit multiple .apk's associated as one app to the Play Store. So, if the higher res files are pushing your app over the 50 meg mark, you can for example exclude the highest res files from the first build and edit `AndroidManifest.xml` to reflect this fact, meaning this .apk will support phones and tablets with X resolution and below. Then, you can do the same thing but only build the .apk for high res devices and edit the same manifest appropriately.

And you are correct--the link you had to remove certain files from a build will not work with RapidGame. However, depending on your code and the API calls you make, you might be able to get away with simply moving the files you don't want included in the assets to a temporary directory before you run `make distribution`, so that only the files you want in that build are included. I forget exactly how different resolutions are handled in Android/Android NDK/Cocos2dx (haven't had a lot of free time recently), but you may want to get a better understanding of how it works, because it may turn out you have to do nothing more than that. Otherwise, you may need to refactor your code to better handle resolutions. But it is possible and a solution can probably be found and implemented within a reasonable amount of time.

So as long as you follow the [rules of submitting multiples .apk's](http://developer.android.com/google/play/publishing/multiple-apks.html), it's just a matter of making at least 2 .apk's that both work well with their respective assets.

**Comment by jonnyijapan** [comment]
Ok got it. I will consider sending several asks. Thanks!
